GovUK.xcodeproj/xcshareddata/IDETemplateMacros.plist, Production/govuk_ios/SupportingFiles/AppDelegate.swift, Production/govuk_ios/SupportingFiles/SceneDelegate.swift, Production/govuk_ios/ViewControllers/ViewController.swift, Tests/govuk_ios/govuk_ios_ui_tests/GovUKUITests.swift, Tests/govuk_ios/govuk_ios_ui_tests/GovUKUITestsLaunchTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/GovUKTests.swift
Removing all headers and the template.
This still leaves an empty comment at the top of new files that needs to be deleted when creating a new file. 
It's better to have an empty comment than the current header in case someone forgets to delete it.
=> Remove default headers

GovUK.xcodeproj/project.pbxproj
Currently SwiftLint is not running on incremental builds which means that we are only identifying listing problems when they hit the pipeline runner. Changing this configuration ensures that the linter will run on all builds.
=> Set swiftlint to run on incremental builds

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/SupportingFiles/Info.plist, TestFlight/WhatToTest.en-GB.txt
This will allow us to update WhatToTest for TestFlight builds from the code.
This will prevent needing to manually declare conformance when uploading builds to TestFlight/ App Store.
=> Added compliance declaration to Info.plist and WhatToTest

Production/govuk_ios/Builders/ViewControllerBuilder.swift, Production/govuk_ios/Model/Analytics/TrackableScreen.swift, Production/govuk_ios/ViewControllers/BaseViewController.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/AnalyticsConsentViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/LaunchViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SearchViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SettingsViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/MockBaseViewController.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Clients/FirebaseClientTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/BaseCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Extensions/UIKit/UIViewController+ExtensionsTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AnalyticsServiceTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/BaseViewControllerTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/SearchViewControllerTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/SettingsViewControllerTests.swift
There are some unit tests that would benefit from running `.serialized` because they use static vars to assert against.
Added Swift Testing to achieve this without making all tests run in serial.
=> Added Swift Testing

Production/govuk_ios/Views/Search/SearchErrorView.swift
Prevously, if the user met an error screen with no link, e.g no results and then straight after returned a generic error with a link, the link would still be hidden. We now set the hidden flag to false when there is a link.
=> Fix search error link bug

Production/govuk_ios/SwiftUIViews/AppUnavailableContainerView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AppUnavailableViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AppUnavailableViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
Ignore bottom safe area so view elements are positioned inline with designs
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-589)
[Figma link](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=710-16944&node-type=frame&t=EbzBkYwf47XOvILr-0)
=> GOVUKAPP-589 Global ON / OFF switch: Ignore bottom safe area

Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift, Production/govuk_ios/Views/Topics/EditTopicsView.swift
Fix VO to read Topics before Edit button on home page. 
Edit Topics page subtitle now scrolls
=> Fix VO nav order, and scrolling of subtitle

Production/govuk_ios/Extensions/UIKit/UITabBarAppearance+GOVUK.swift
Designs call for the tab bar to be opaque.  For whatever reason, configureWithOpaqueAppearance() does work on all screens, but leaving as the default does.
=> Use default (opaque) appearance for tab bar

.github/workflows/unit_test.yml
Caching dd corrupts the coverage report for sonar.
=> Remove derived data cache

Production/govuk_ios/Resources/Strings/Topics.xcstrings, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TopicOnboardingViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TopicOnboardingViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
This pr corrects a typo in the topic onboarding as It should say "home page" and not "home pages".
=> Correct typo in topic onboarding

Production/govuk_ios/Views/Common/GroupedListTableViewCell.swift
When editing, remove hint and trait.  Add back in when editing ends.
=> GOVUKAPP-873: Remove accessibility hint when editing

Production/govuk_ios/ViewControllers/RecentActivityListViewController.swift, Production/govuk_ios/Views/Common/GroupedListTableViewCell.swift
call invalidateIntrinsicContentSize() instead of reloading snapshot
=> GOVUKAPP-896:  title wrap when editing, part 2

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Model/Topics/TopicOnboardingCardModel.swift, Production/govuk_ios/ViewControllers/TopicOnboardingViewController.swift, Production/govuk_ios/ViewModels/Topics/TopicOnboardingViewModel.swift, Production/govuk_ios/Views/Topics/TopicOnboardingCard.swift, Production/govuk_ios/Views/Topics/TopicOnboardingListView.swift, Production/govuk_ios/Views/Topics/TopicSelectedView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TopicOnboardingViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TopicOnboardingViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicOnboardingViewModelTests.swift
PR updates the way the topics are selected in onoarding.
We now set it on the topic object and then roll back the MOC should the user press "Skip." This approach is still up for debate, and I have a spike planned to test a couple of alternative approaches at some point.
The PR also fixes some layout issues in the layout of the cards.
=> Onboarding topics

Production/govuk_ios/Model/AppConfig/AppConfig.swift, Tests/govuk_ios/govuk_ios_unit_tests/Arrangers/Model/AppConfig+Arrangers.swift
The signature is to no longer be passed as part of the response body, as we get it from the headers now.
Remove the "signature" parameter to insure responses are parsed correctly when the change is pushed on the back end
=> Remove signature from AppConfig

Production/govuk_ios/Views/Topics/TopicSelectedView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TopicOnboardingViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TopicOnboardingViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
Updated selected icon to include correct spacing and check image when selected
=> Updated selected icon for topic selection

Production/govuk_ios/ViewControllers/HomeViewController.swift
Going to PYV or Topics and back to the homepage occasionally made it seem like there was a pull to refresh on the homepage.
This seems to have been something to do with the large navigation title.
Setting `largeTitleDisplayMode = .never` appears to resolve the issue.
=> Homepage insets

Production/govuk_ios/Extensions/UIKit/UIButton+Convenience.swift, Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift
Make sure edit button label adjusts size on accessibility change.
Adjust titleLabel compression on largest font size so Edit button remains visible
=> GOVUKAPP-974:  edit topics button accessibility size change

Production/govuk_ios/Extensions/Container/Container+DataStores.swift, Production/govuk_ios/Repositories/CoreDataRepository.swift, Tests/govuk_ios/shared/Arrangers/Repositories/CoreDataRepository+Arrangers.swift
Moved core data model to Container to prevent warnings during unit testing. This is not ideal, if we manage to prevent the app launching a real DB during unit tests, we can remove this.
When the persistent stores are loaded, we use the completion handler with the description to "snatch" the store's URL and mark it as excluded from backup.
Should this not work 100% of the time, we might want to expose a method and call it when the app enters background or similar.
=> GOVUKAPP-838 Prevent CoreData backup

Production/govuk_ios/Coordinators/BaseCoordinator.swift, Production/govuk_ios/Coordinators/EditTopicsCoordinator.swift, Production/govuk_ios/Coordinators/HomeCoordinator.swift, Production/govuk_ios/Coordinators/SettingsCoordinator.swift, Production/govuk_ios/Coordinators/TabCoordinator.swift, Production/govuk_ios/Extensions/UIKit/UIViewController+Extensions.swift, Production/govuk_ios/ViewControllers/HomeViewController.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Coordinators/MockBaseCoordinator.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/ViewControllers/MockHomeViewController.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/EditTopicsCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/HomeCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/TabCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/HomeViewControllerTests.swift
Added TabItemCoordinatorInterface protocol, defining a method to invoke when an already selected tab is reselected.
All TabItemCoordinators now implement this protocol
This allows HomeCoordinator to invoke scroll to top on HomeViewController when the home tab is reselected.
=> Govukapp-865 ios home button behavior

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Model/RecentActivity/RecentActivitySection.swift, Production/govuk_ios/Resources/Strings/RecentActivity.xcstrings, Production/govuk_ios/ViewControllers/RecentActivityListViewController.swift
Following accessibility audit.
=> [GOVUKAPP-1024] Update edit actions voice over text

Production/govuk_ios/Extensions/Analytics/AppEvent+Search.swift, Production/govuk_ios/ViewControllers/SearchViewController.swift, Production/govuk_ios/ViewModels/SearchViewModel.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SearchViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Analytics/AppEvent+SearchTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SearchViewModelTests.swift
Renames searchButtonPressed to didInvokeSearch which is a bit more
reflective of its responsibilities (history + autocomplete).
Uses delegate method for handling the search return vs adding a target
which is cleaner as don't need to conform to `@objc` (e.g for the type
enum).
=> [GOVUKAPP-1074] Add analytics for history + suggestions

Production/govuk_ios/Resources/Strings/Topics.xcstrings, Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift, Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_topicsError_darK_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_topicsError_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicsWidgetViewModelTests.swift
Added AppErrorView to TopicsWidgetView
Updated error handling.  This required a refactor as we had been fetching the remote topics on view model instantiation, and saving the resulting error to the view model.  Just checking the error state could result in a race condition as the view may have finished loading before the result came back.   
Now the fetch is performed separately during view set up, and the view passes an error handler to the model when it is ready.
=> govukapp-1038 topics cant be displayed

.github/workflows/alpha.yml, .github/workflows/beta.yml, .github/workflows/schedule.yml, .github/workflows/sonar_scan_branch.yml, .github/workflows/sonar_scan_pr.yml, GovUK.xcodeproj/xcshareddata/xcschemes/GovUK.xcscheme, GovUK.xcodeproj/xcshareddata/xcschemes/GovUKAlpha.xcscheme, GovUK.xcodeproj/xcshareddata/xcschemes/GovUKDev.xcscheme
Temporarily setting java version, seems to allow us to brew install the older (unbroken) version of sonar-scanner.
Will revert when an updated sonar-scanner is released with the fix
=> Add schedule steps

Production/govuk_ios/Views/Search/SearchResultCell.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SearchViewControllerSnapshotTests/test_search_successResponse_withResults_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SearchViewControllerSnapshotTests.swift
When search results have a blank description there is extra padding applied even though the description label isn't visible. Attempted to mark the bodyLabel as hidden (`isHidden`) but the extra 8pts padding [1] still persists and thus I've just defined the constraint again, minus the constant. 
[1]: https://github.com/alphagov/govuk-mobile-ios-app/blob/be436a44072a249c7fbcdeb69364c3b822f1d51b/Production/govuk_ios/Views/Search/SearchResultCell.swift#L121-L123
=> [GOVUKAPP-1093] Remove extra padding for empty desc

Production/govuk_ios/Views/Home/Topics/TopicCard.swift, Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift
Make topic cards larger depending on the dynamic type set. The main
driver of this is to prevent multiple line hyphenation of words
in the topic titles. Topic cards will now break if a word is larger than
the available card width space.
More info in the commits ->
=> [GOVUKAPP-1130] Topics widget card breaking

.github/workflows/sonar_scan_branch.yml, .github/workflows/sonar_scan_pr.yml
For sonar-scanner versions 7.xx we're getting a Java runtime error. Brew
seems to either install either 6.2 or 7.0 everytime we run `brew install
sonar-scanner`. 
6.2 builds pass fine. There doesn't seem to be an easy
way to install specific versions of packages through brew.
The below error is returned for version 7.0 and is a known bug. There is
a workaround [1] implemented in this PR. Tested on versions 6.2 and 7.0
and run successfully.
An alternative workaround is to ensure we're using Java 17 which doesn't
have the issue (implemented [2] and then revoked).
The problem should be fixed in future versions of sonar-scanner and thus
we can then remove the env vars.
```
...
Caused by: java.io.IOException: password supplied for keystore that does not require one
```
Also moves setting env …
=> Adds fix for Java runtime error for branch worflow

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Coordinators/HomeCoordinator.swift, Production/govuk_ios/Extensions/Analytics/AppEvent+ECommerce.swift, Production/govuk_ios/Model/Analytics/ECommerceItem.swift, Production/govuk_ios/Model/Analytics/HomeCommerceItem.swift, Production/govuk_ios/Model/Analytics/TopicCommerceItem.swift, Production/govuk_ios/ViewModels/Topics/StepByStepsViewModel.swift, Production/govuk_ios/ViewModels/Topics/TopicDetailViewModel.swift, Production/govuk_ios/ViewModels/Topics/TopicDetailViewModelInterface.swift, Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift, Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Analytics/AppEvent+EcommerceTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/HomeViewControllerTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicsWidgetViewModelTests.swift
Add ecommerce tracking to the home page, as per [spec](https://docs.google.com/spreadsheets/d/1GJzMF7F3Xgujv2sowfNu3HyYGxmQ3rF3xqHye24rb-o/edit?pli=1&gid=1502926465#gid=1502926465)
Refactored EcommerceItem to be a protocol, with implementations of TopicsCommerceItem and HomeCommerceItem.  Moved all of this to govuk_ios, as did not seem general enough for GOVKit.
Added convenience methods for select_item events for home and topics.
At present, view_item_list homepage commerce event is fired on change of selected topics (core data save), not page view, as when page appears topics not yet loaded.
=> govukapp-1148 home ecommerce tracking

Production/govuk_ios/Coordinators/HomeCoordinator.swift, Production/govuk_ios/ViewControllers/HomeViewController.swift, Production/govuk_ios/ViewModels/HomeViewModel.swift, Production/govuk_ios/ViewModels/Topics/StepByStepsViewModel.swift, Production/govuk_ios/ViewModels/Topics/TopicDetailViewModel.swift, Production/govuk_ios/ViewModels/Topics/TopicDetailViewModelInterface.swift, Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift, Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift, Production/govuk_ios/Views/Topics/TopicDetailView.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicsWidgetViewModelTests.swift
Add flags to help track state of topic loading, so that e-commerce events can be fired based on screen appearances.
=> Fixes for e-commerce event firing

Production/govuk_ios/Coordinators/HomeCoordinator.swift, Production/govuk_ios/Extensions/UIKit/UIViewController+Extensions.swift, Production/govuk_ios/ViewControllers/HomeContentViewController.swift, Production/govuk_ios/ViewControllers/HomeViewController.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/ViewControllers/MockHomeViewController.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/HomeCoordinatorTests.swift
As ContentScrollable / scrollToTop doesn't really capture the full responsibilities of the function in HomeViewController, this has been renamed to ResetsToDefault / resetState.
We need the protocol for the HomeCoordinatorTests.
=> Updates ContentScrollable to ResetsToDefault

GOVKit/Sources/GOVKit/SwiftUIViews/AppErrorView.swift, Production/govuk_ios/ViewControllers/SearchHistoryViewController.swift, Production/govuk_ios/ViewControllers/SearchViewController.swift, Production/govuk_ios/Views/Search/SearchHistoryCell.swift
The gray square was caused by the AppErrorView's action button reacting to buttonShapes being switched on.  As it had no title, only an empty square was visible.  If there is no title, the opacity is set to 0 to hide it.
For searchHistory, use a filled() UIButton.Configuration to prevent a color change when buttonShapes is switched on.
=> govukapp-1295: gray squares when button shapes on

GOVKit/Sources/GOVKit/Views/Common/TopAlignedBarButtonItem.swift
Set adjustsFontForContentSizeCategory = true for TopAlignedBarButtonItems.  This has the effect of making the items adhere to the font metrics for navigation and tool bars, which prevents them from scaling so large they no longer fit within the tool bar.
=> govukapp-1296:  Remove button text wrapping

Production/govuk_ios/Services/Notifications/NotificationService.swift, Production/govuk_ios/SupportingFiles/Info.plist, Production/govuk_ios/SupportingFiles/SceneDelegate.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/NotificationServiceTests.swift, Tests/govuk_ios/shared/Mocks/Services/MockNotificationService.swift
- Add click listener to notification clicks. 
- Handle notifications additional data.
- Prevent launch urls being opened from One Signal notifications.
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-1132)
=> GOVUKAPP-1132 App deep links from notification

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Model/LocalAuthority/LocalAuthorityItem.swift, Production/govuk_ios/Repositories/GOV.xcdatamodeld/GOV_v2.xcdatamodel/contents, Production/govuk_ios/Repositories/LocalAuthorityRepository.swift, Production/govuk_ios/Services/LocalAuthorityService.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Repositories/MockLocalAuthorityRepository.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Repositories/LocalAuthorityRepositoryTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/LocalAuthortiyServiceTests.swift
Add a LocalAuthorityRepository and corresponding core data model updates and classes.
As users will only ever have one local authority, or a parent-child pair, delete old authority if saving a new one.
=> GOVUKAPP-1355: Store Local Authority

Production/govuk_ios/Builders/CoordinatorBuilder.swift, Production/govuk_ios/Builders/ViewControllerBuilder.swift, Production/govuk_ios/Coordinators/AppCoordinator.swift, Production/govuk_ios/Coordinators/SettingsCoordinator.swift, Production/govuk_ios/Coordinators/SignOutConfirmationCoordinator.swift, Production/govuk_ios/Coordinators/SignedOutCoordinator.swift, Production/govuk_ios/Coordinators/TabCoordinator.swift, Production/govuk_ios/Resources/Strings/SignOut.xcstrings, Production/govuk_ios/Services/AuthenticationService.swift, Production/govuk_ios/ViewModels/SignOutConfirmationViewModel.swift, Production/govuk_ios/ViewModels/SignedOutViewModel.swift, Production/govuk_ios/Views/SignOut/SignedOutView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SignedOutViewControllerSnapshotTests/test_loadInNavigationController_with_error_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SignedOutViewControllerSnapshotTests/test_loadInNavigationController_with_error_light_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SignOutConfirmationViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SignedOutViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockCoordinatorBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/CoordinatorBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AppCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/SignOutConfirmationCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/SignedOutCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/TabCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SignOutConfirmationViewModelTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SignedOutViewModelTests.swift
Enhance signed out view to allow error display if sign out fails.
Refactor coordination to handle sign out cancellation, sign out success, and sign out failure scenarios.
=> govukapp-1557: unsuccessful sign out

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Builders/CoordinatorBuilder.swift, Production/govuk_ios/Builders/ViewControllerBuilder.swift, Production/govuk_ios/Coordinators/AuthenticationCoordinator.swift, Production/govuk_ios/Coordinators/AuthenticationOnboardingCoordinator.swift, Production/govuk_ios/Coordinators/SignInErrorCoordinator.swift, Production/govuk_ios/Resources/Strings/SignOut.xcstrings, Production/govuk_ios/ViewModels/AuthenticationInfoViewModelInterface.swift, Production/govuk_ios/ViewModels/SignInErrorViewModel.swift, Production/govuk_ios/ViewModels/SignedOutViewModel.swift, Production/govuk_ios/Views/SignOut/AuthenticationInfoView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SignInErrorViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SignInErrorViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SignInErrorViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SignedOutViewControllerSnapshotTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockCoordinatorBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/CoordinatorBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AppCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AuthenticationCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AuthenticationOnboardingCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/SignInErrorCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SignInErrorViewModelTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SignedOutViewModelTests.swift
Refactored sign out view to be more generic so it could also be used for sign in error view.
Sign in errors are now propagated up to AuthenticationOnboardingCoordinator for handling of display
NOTE:  the showError() method is internal (not private) as this was the only way I could see it be made testable without considerable refactoring.
=> govukapp-1555 sign in error

Production/govuk_ios/Resources/Strings/LocalAuthority.xcstrings, Production/govuk_ios/ViewModels/StoredLocalAuthorityWidgetViewModel.swift, Production/govuk_ios/Views/Home/LocalAuthority/StoredLocalAuthorityCardView.swift, Production/govuk_ios/Views/Home/LocalAuthority/StoredLocalAuthorityWidgetView.swift
VO fixes:  
- Add alt text for local authority edit button.
- Reconfigure accessibility elements on local council card to only read out link info once.
=> Edit local authority VO fixes

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Extensions/Container/Container+APIClients.swift, Production/govuk_ios/Model/LocalAuthority/LocalAuthorityResponse.swift, Production/govuk_ios/Networking/APIServiceClient.swift, Production/govuk_ios/Networking/ResponseHandler.swift, Production/govuk_ios/ServiceClients/LocalAuthorityResponseHandler.swift, Production/govuk_ios/ServiceClients/LocalAuthorityServiceClient.swift, Production/govuk_ios/ViewModels/LocalAuthority/LocalAuthorityPostcodeEntryViewModel.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Networking/APIServiceClientTests+LocalAuthority.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ServiceClients/LocalAuthorityServiceClientTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/LocalAuthortiyServiceTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/LocalAuthority/LocalAuthorityPostcodeEntryViewmodelTests.swift
Refactor of how we handle errors so that we can examine HTTPResponse status codes if needed.
The APIServiceClient now accepts an optional ResponseHandler on initialization.
If this handler is present, it intercepts the URLResponse and possible error for processing (i.e., examine the response status), then returns an optional error.
For LocalAuthority, this means we no longer look for an error message in response data.
=> Local authority error handling

GOVKit/Sources/GOVKit/Extensions/UIKit/URLOpener.swift, GOVKit/Tests/GOVKitTests/Specs/Extensions/UIKit/URLOpenerTests.swift, GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Builders/CoordinatorBuilder.swift, Production/govuk_ios/Coordinators/Launch/JailbreakCoordinator.swift, Production/govuk_ios/Coordinators/Launch/PreAuthCoordinator.swift, Production/govuk_ios/Extensions/Container/Container+Services.swift, Production/govuk_ios/Services/JailbreakDetectionService.swift, Production/govuk_ios/ViewModels/AppUnavailableContainerViewModel.swift, Production/govuk_ios/Wrappers/DynamicLibraryWrapper.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockCoordinatorBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Foundation/MockFileManager.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Jailbreak/MockDynamicLibrary.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Jailbreak/MockJailbreakURLOpener.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Services/MockJailbreakDetectionService.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/CoordinatorBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/JailbreakCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/PreAuthCoordinatorTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/JailbreakDetectionServiceTests.swift
Add a jailbreak detection service, which tests for the presence of forbidden files, libraries, and device permissions.
Service is called first thing on launch, and if a jailbreak is detected, the "app not available" screen is shown
=> govukapp 1561 jailbreak detection

GovUK.xcodeproj/project.pbxproj, Production/govuk_ios/Extensions/Analytics/AppEvent+Chat.swift, Production/govuk_ios/ViewModels/Chat/ChatCellViewModel.swift, Production/govuk_ios/ViewModels/Chat/ChatConsentOnboardingViewModel.swift, Production/govuk_ios/ViewModels/Chat/ChatInfoOnboardingViewModel.swift, Production/govuk_ios/ViewModels/Chat/ChatViewModel.swift, Production/govuk_ios/Views/Chat/ChatActionView.swift, Production/govuk_ios/Views/Chat/ChatCellView.swift, Production/govuk_ios/Views/Chat/ChatConsentOnboardingView.swift, Production/govuk_ios/Views/Chat/ChatView.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatCellViewModelTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatConsentOnboardingViewModelTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatInfoOnboardingViewModelTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatViewModelTests.swift
Add analytics tracking for chat window and onboarding. 
Not tracking initial action menu tap as you can't easily attach a tap gesture to a Menu element in Swift UI.
More info in commits ->
=> [GOVUKAPP-2273] Feature/add chat analytics

Production/govuk_ios/SupportingFiles/SceneDelegate.swift, Production/govuk_ios/ViewModels/Chat/ChatViewModel.swift, Production/govuk_ios/Views/Chat/ChatView.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatViewModelTests.swift
Tracks question answer response. The event can fire when chat isn't visible, however  
Tracks when a user moves off chat window, either in app or when the app is backgrounded. The event can fire when chat isn't visible, so these events and / or events like screen views can be used to work out if a user has moved off the chat window. 
A distinct event leaving will also be useful to calculate the time taken for a user leaves.  
A future piece of work will differentiate between a failed ask question, failed poll or successful poll response. For now we'll return response tracking even if there is an error.
=> [GOVUKAPP-2317] Tracks question answer response

Production/govuk_ios/ViewControllers/HomeContentViewController.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/HomeContentViewControllerTests.swift
Add a type parameter to home screen tracking that specifies chat opt in status.
This required creation of cached value of the opt in status for thread safety reasons.
The implementation may need to be revisited if user is allowed to change their status after initial onboarding - e.g. if a switch is added to settings.
=> govukapp-2529:  chat opt in analytics

Production/govuk_ios/ViewModels/Topics/StepByStepsViewModel.swift, Production/govuk_ios/ViewModels/Topics/TopicDetailViewModel.swift
Popular pages duplication bug 
- Use 'UUID' rather than 'content title' as the identifiable 'id' as some content titles are the same causing id conflict (this bug).
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-2531)
=> GOVUKAPP-2531 Popular pages duplication bug 

Production/govuk_ios/Views/Chat/ChatCellView.swift, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.ChatViewControllerSnapshotTests/test_loadInNavigationController_noSources_dark_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.ChatViewControllerSnapshotTests/test_loadInNavigationController_noSources_light_rendersCorrectly@3x.png, Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/ChatViewControllerSnapshotTests.swift
Only show chat accuracy warning if there are source links included in response.
Add tests for no sources case
=> govukapp-2547: Conditionally show chat accuracy warning

Production/govuk_ios/Resources/Strings/Chat.xcstrings, Production/govuk_ios/ViewModels/Chat/ChatCellViewModel.swift, Production/govuk_ios/Views/Chat/ChatCellView.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatCellViewModelTests.swift
Add context menu to chat cells allowing copy to clipboard.
Markdown is stripped before copying
Includes accuracy warning and links when required
=> govvukapp-2048:  Chat copy to clipboard

Production/govuk_ios/Builders/ViewControllerBuilder.swift, Production/govuk_ios/Coordinators/Launch/WelcomeOnboardingCoordinator.swift, Production/govuk_ios/Coordinators/SignInSuccessCoordinator.swift, Production/govuk_ios/ViewModels/InfoViewModelInterface.swift, Production/govuk_ios/ViewModels/WelcomeOnboardingViewModel.swift, Production/govuk_ios/Views/Common/Info/InfoView.swift, Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/WelcomeOnboardingCoordinatorTests.swift
In order to show a loading indicator while we wait for authentication to finish,  InfoView has been modified to overlay the indicator if supported by the view model.
- A new protocol, ProgressIndicating, was added to optionally show/hide a loading indicator overlay on the Infoview.  If the viewModel for the InfoView implements this protocol (in addition to InfoViewModelProtocol), then it can control the presentation of the loading indicator.  As well as showing and hiding, the presentation can be delayed.  This was added so that the loading indicator does not appear before the authentication modal has been fully presented.
- In order for this to work, InfoViewModelProtocol needs to be an ObservableObject.  Swift requires ObservableObjects to be concrete implementations, so it was …
=> Govukapp-2450: Show loading indicator during login while waiting for auth to finish

Production/govuk_ios/Services/Analytics/AnalyticsService.swift, Production/govuk_ios/Services/ReturningUserService.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AnalyticsServiceTests.swift, Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/ReturningUserServiceTests.swift
If a user logs in and a previous id token isn't stored, rather than throw an error, just treat them as a new user.
=> Fix return user missing issue.

Production/govuk_ios/Coordinators/TabCoordinator.swift
previousTabIndex wasn't being set when a deeplink was being processed (chat navigation from home screen), resulting in inconsistent tabs being selected when a user cancelled out from chat onboarding, now previousTabIndex is being set, the user will return to the original tab (in this case home screen from chat widget).
=> Fix cancel behaviour on chat onboarding
