alphagov/govuk-mobile-ios-app

- .github/workflows/alpha.yaml
- .github/workflows/lint.yml
- .github/workflows/pull_request.yaml
- .github/workflows/sonar_scan_branch.yml
- .github/workflows/sonar_scan_pr.yml
- .github/workflows/unit_test.yml
- .gitignore
- Fastlane/.build.yml
- Fastlane/Fastfile
- Fastlane/configuration.rb
- Gemfile
- Gemfile.lock
- GovUK.xcodeproj/project.pbxproj
- sonar-project.properties
Co-auth: @batesyuk 
JIRA: https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-441
> Add Sonar scans and code coverage

- .github/workflows/lint.yml
- .github/workflows/sonar_scan_branch.yml
- .github/workflows/sonar_scan_pr.yml
- .github/workflows/unit_test.yml
JIRA: https://govukverify.atlassian.net/jira/software/projects/GOVAPP/boards/405?selectedIssue=GOVAPP-458
> Pin action versions

- .gitattributes
- .gitignore
- GovUK.xcodeproj/project.pbxproj
- GovUK.xcodeproj/xcshareddata/xcschemes/GovUK.xcscheme
- Tests/GovUK.xctestplan
- Tests/govuk_ios/govuk_ios_snapshot_tests/Helpers/SnapshotTestCase.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LaunchViewControllerTests/test_loadInNavigationController_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TestViewControllerTests/test_loadInNavigationController_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TestViewControllerTests/test_loadInNavigationController_withModalAction_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/LaunchViewControllerTests.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/TestViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/BaseViewControllerTests.swift
- Tests/govuk_ios/shared/SupportingFiles/TestAppDelegate.swift
Adding the ability to snapshot test views.
I added some initial tests, but the views aren't fully designed yet, so I haven't gone mad.
> GOVUKAPP 103 - Added snapshot tests

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Coordinators/OnboardingCoordinator.swift
- Production/govuk_ios/Extensions/Container/Container+Services.swift
- Production/govuk_ios/Services/AnalyticsService+Onboarding.swift
- Production/govuk_ios/Services/OnboardingService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Arrangers/Onboarding/OnboardingSlide+Arrangers.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/OnboardingCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AnalyticsService+OnboardingTests.swift
- Tests/govuk_ios/shared/Mocks/MockAnalyticsService.swift
Related Ticker :https://govukverify.atlassian.net/jira/software/c/projects/GOVUKAPP/boards/559?selectedIssue=GOVUKAPP-510
This pr bridges the onboarding functionality in the onboarding module to the main app.
> Add Onboarding Analytics

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Resources/en.lproj/Localizable.strings
- Production/govuk_ios/ViewControllers/LaunchViewController.swift
Add accessibility label to app launch splash screen
> GOVUKAPP-670: Splash Screen Alt Text

- .github/workflows/upload_internal.yaml
- Fastlane/Fastfile
- Fastlane/configuration.rb
> GOVUKAPP-665 Automate TestFlight deployments

- .github/workflows/alpha.yaml
- .github/workflows/deploy.yaml
- .github/workflows/sonar_scan_branch.yml
* Added deploy step for develop branch
* Add property to wait for sonar quality gate before continuing Actions
> GOVUKAPP-665 Deploy TestFlight

- Fastlane/Fastfile
- Fastlane/README.md
> GOVUKAPP-665 TestFlight Deploy

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/Coordinators/SettingsCoordinator.swift
- Production/govuk_ios/Extensions/Foundation/String+Extensions.swift
- Production/govuk_ios/Resources/en.lproj/Localizable.strings
- Production/govuk_ios/SwiftUIViews/GroupedList/GroupedList.swift
- Production/govuk_ios/SwiftUIViews/GroupedList/GroupedListRowView.swift
- Production/govuk_ios/ViewModels/GroupedListSection.swift
- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_preview_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SettingsViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Models/SettingsViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/SettingsViewControllerTests.swift
- Tests/govuk_ios/shared/Mocks/MockAnalyticsService.swift
Added a ToggleRow to GroupedList rows.
Added new section/row in sections for turning anaytics on/off via the analytics service.
Added localizations and convenience method for accessing them.
> Add toggle in settings to turn analytics on/off

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/Coordinators/HomeCoordinator.swift
- Production/govuk_ios/Coordinators/SearchCoordinator.swift
- Production/govuk_ios/Extensions/UIKit/UIBarButtonItem+Extensions.swift
- Production/govuk_ios/Extensions/UIKit/UIViewController+Extensions.swift
- Production/govuk_ios/ViewControllers/SearchViewController.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Helpers/SnapshotTestCase.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/AnalyticsConsentViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SearchViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SettingsViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockCoordinatorBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Coordinators/MockNavigationController.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/MockBaseViewController.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/CoordinatorBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Clients/FirebaseClientTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/SearchCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Extensions/UIKit/UIViewController+ExtensionsTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/SearchViewControllerTests.swift
Added Homepage tracking when closing search.
Updated naming for snapshot helpers.
> GOVUKAPP-714 Page view tracking

- .github/workflows/alpha.yml
- .github/workflows/sonar_scan_branch.yml
- .github/workflows/sonar_scan_pr.yml
- .github/workflows/unit_test.yml
- .github/workflows/upload_internal.yml
- Fastlane/Fastfile
- Gemfile.lock
- GovUK.xcodeproj/project.pbxproj
- GovUK.xcodeproj/xcshareddata/xcschemes/GovUK.xcscheme
- Tests/govuk_ios/govuk_ios_snapshot_tests/Helpers/SnapshotTestCase.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AnalyticsConsentCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/BaseCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Networking/APIServiceClientTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AnalyticsServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Views/AnimationViewTests.swift
- Updated APIServiceClientTests to be serialized
Commented test_viewControllerPopped_finalViewController_callsFinish until we can get it working reliably
> Updated APIServiceClientTests

- Fastlane/.build.yml
- Production/govuk_ios/Extensions/Analytics/AppEvent+Convenience.swift
- Production/govuk_ios/ViewModels/SearchViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Analytics/AppEvent+ConvenienceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Models/SearchViewModelTests.swift
Applied updated tracking params for pressing on a search result item. See the[ tracking doc](https://docs.google.com/spreadsheets/d/1GJzMF7F3Xgujv2sowfNu3HyYGxmQ3rF3xqHye24rb-o/edit?gid=474006648#gid=474006648. ) for more details.
> GOVUKAPP-567: Update tracking for search item

- .github/workflows/unit_test.yml
Adds a 30 minute timeout to unit test runs
> Add 30 minute timeout to unit tests

- Production/govuk_ios/ViewControllers/BaseViewController.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/BaseViewControllerTests.swift
Causing status bar on home screen to be transparent in light mode.
> Use default status bar style

- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/BaseCoordinatorTests.swift
- Moved BaseCoordinatorTests to Swift Testing
> BaseCoordinatorTests -> Swift Testing

- Production/govuk_ios/Model/AppConfig/Feature.swift
- Production/govuk_ios/Resources/RemoteConfigResponse.json
- Production/govuk_ios/Services/AppConfigService.swift
- Production/govuk_ios/Services/TopicsService.swift
- Production/govuk_ios/ViewModels/HomeViewModel.swift
- Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift
- Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockAppConfigService.swift
Added feature flag for topics
Added logic to merge remote and local AppConfig so that if feature is missing from remote config we can still toggle locally.
Updated TopicsWidget to re-layout topic cards on orientation change, as this was missed in last ticket
> feature flag for topics

- Production/govuk_ios/Resources/Strings/RecentActivity.xcstrings
- Production/govuk_ios/Views/RecentlyViewed/RecentActivityContainerView.swift
this pr corrects the test on the error screen and removes and unnecessary accessibility label
> View recently visited items - Text Correction 

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Coordinators/AppCoordinator.swift
- Production/govuk_ios/Coordinators/AppRecommendUpdateCoordinator.swift
- Production/govuk_ios/Resources/Strings/AppAvailability.xcstrings
- Production/govuk_ios/Resources/Strings/Common.xcstrings
- Production/govuk_ios/Services/AppConfigService.swift
- Production/govuk_ios/SwiftUIViews/AppRecommendUpdateContainerView.swift
- Production/govuk_ios/ViewModels/AppForcedUpdateContainerViewModel.swift
- Production/govuk_ios/ViewModels/AppRecommendUpdateContainerViewModel.swift
- Production/govuk_ios/ViewModels/AppUnavailableContainerViewModel.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AppRecommendUpdateViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AppRecommendUpdateViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/AppRecommendUpdateViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/AppRecommendUpdateCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AppConfigServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/AppForcedUpdateContainerViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/AppRecommendUpdateContainerViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/AppUnavailableContainerViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockAppConfigService.swift
Add new update recommendation screen and logic to show it
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-593)
[Figma link](https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=363-6730&node-type=section&t=JmpogWWSQbIkQJ5x-0)
> GOVUKAPP-593 Update Recommendation

- Production/govuk_ios/Coordinators/HomeCoordinator.swift
- Production/govuk_ios/ViewModels/Topics/EditTopicsViewModel.swift
- Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift
- Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift
- Production/govuk_ios/Views/Topics/EditTopicsView.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.EditTopicsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.EditTopicsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Models/EditTopicsViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Models/TopicsWidgetViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/TopicsServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/HomeViewControllerTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockTopicsService.swift
* Update home screen button colour
* Update done button colour
* Save selections when switch is toggled, rather than when done is pressed (issue with drag to dismiss screen not updating selections on home page)
> Update edit topics colours and save position

- Production/govuk_ios/Model/AppConfig/Feature.swift
- Production/govuk_ios/Resources/RemoteConfigResponse.json
- Production/govuk_ios/ViewModels/HomeViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockAppConfigService.swift
- Add feature flag and logic for Pages You've Visited
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-775)
> GOVUKAPP-775 Feature Flag for Pages You've Visited

- Production/govuk_ios/Resources/Constants.swift
- Production/govuk_ios/Resources/Strings/Settings.xcstrings
- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SettingsViewModelTests.swift
Added help and feedback link to the settings page
> GOVUKAPP-813  -  Help and feedback link

- Production/govuk_ios/ViewControllers/RecentActivityListViewController.swift
- Only show the edit button when there are visited pages to edit
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-828)
> GOVUKAPP-828 Hide edit button

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/Coordinators/EditTopicsCoordinator.swift
- Production/govuk_ios/Coordinators/HomeCoordinator.swift
- Production/govuk_ios/Resources/Strings/Home.xcstrings
- Production/govuk_ios/ViewModels/HomeViewModel.swift
- Production/govuk_ios/ViewModels/RecentActivityWidgetViewModel.swift
- Production/govuk_ios/ViewModels/SearchWidgetViewModel.swift
- Production/govuk_ios/ViewModels/Topics/EditTopicsViewModel.swift
- Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift
- Production/govuk_ios/ViewModels/WidgetViewModel.swift
- Production/govuk_ios/Views/Home/RecentActivtyWidget.swift
- Production/govuk_ios/Views/Home/SearchWidgetStackView.swift
- Production/govuk_ios/Views/Home/Topics/TopicsWidgetView.swift
- Production/govuk_ios/Views/Home/WidgetView.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/EditTopicsViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/CoordinatorBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/EditTopicsCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/HomeCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Models/EditTopicsViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Models/TopicsWidgetViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/HomeViewControllerTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockTopicsService.swift
Next to impossible to add unit test for search press event... will look into it later
> Update widget events

- Production/govuk_ios/Resources/Constants.swift
- Production/govuk_ios/Resources/Strings/Settings.xcstrings
- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SettingsViewModelTests.swift
Figma design: https://www.figma.com/design/5u5cvVCgKY3Rng2ADNV30K/2024-07---GOV.UK-app---beta-designs?node-id=1-82987&node-type=instance&t=PLIAMYhaWZ4AdI4q-0
> [GOVUKAPP-841 & GOVUKAPP-842] Update setting links

- Production/govuk_ios/ViewControllers/RecentActivityListViewController.swift
Reload snapshot when toggling editing.
> GOVUKAPP-896: Title wrapping in edit mode

- Production/govuk_ios/Clients/Analytics/FirebaseClient.swift
- Production/govuk_ios/Extensions/Analytics/AppEvent+Function.swift
- Production/govuk_ios/ViewModels/Topics/TopicOnboardingViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Analytics/AppEvent+TopicsTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicOnboardingViewModelTests.swift
- Fixed warnings for merging `additionalParameters` in FirebaseClient
- Set OnboardingTopic selection to buttonFunction event
- Updated `Toggle` casing for all analytics
> Updated analytics

- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/ViewControllers/HomeViewController.swift
- Production/govuk_ios/ViewControllers/HostingViewController.swift
- Add preferredStatusBarStyle to HomeViewController
- Add override for preferredStatusBarStyle in HostingViewController
> PreferredStatusBarStyle

- GovUK.xcodeproj/project.pbxproj
- GovUK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Production/govuk_ios/SwiftUIViews/AnalyticsConsentContainerView.swift
- Production/govuk_ios/SwiftUIViews/AppForcedUpdateContainerView.swift
- Production/govuk_ios/SwiftUIViews/AppRecommendUpdateContainerView.swift
- Production/govuk_ios/SwiftUIViews/AppUnavailableContainerView.swift
Extra navigation bars showing in iOS 15 (iPhone 7)
> iOS15 Fixes

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/Extensions/Foundation/Bundle+AppVersionProvider.swift
- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SettingsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SettingsViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Foundation/Bundle+AppVersionProvider.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SettingsViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/MockAppVersionProvider.swift
- Added (<build_number>) to settings version
> GOVUKAPP-905 Add build number to settings page

- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/SettingsViewModelTests.swift
Fixed opening incorrect urls in settings and added unit tests
> GOVUKAPP-970 Fixed settings URLs

- GovUK.xcodeproj/project.pbxproj
- GovUK.xcodeproj/xcshareddata/xcschemes/GovUK.xcscheme
- GovUK.xcodeproj/xcshareddata/xcschemes/GovUKAlpha.xcscheme
- GovUK.xcodeproj/xcshareddata/xcschemes/GovUKDev.xcscheme
Removed xcconfigs from targets to silence warning
Removed build phase dependency for Firebase config
> Updated settings to silence warnings

- Production/govuk_ios/Repositories/CoreDataRepository.swift
- Added NSPersistentStoreFileProtectionKey to core data
> GOVUKAPP-949 Add encryption flag to CoreData

- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/Coordinators/SettingsCoordinator.swift
- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Production/govuk_ios/Views/Settings/SettingsView.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/SettingsViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/SettingsCoordinatorTests.swift
Added scroll-to-top action when the settings tab button is tapped whilst on the settings tab
> govukapp-995 settings button behavior

- Production/govuk_ios/ViewModels/AppErrorViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicDetailViewModelTests.swift
> Voice over fix

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Extensions/Foundation/Locale+Analytics.swift
- Production/govuk_ios/Extensions/UIKit/UITabBarController+GOVUK.swift
- Production/govuk_ios/ViewControllers/SearchViewController.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AnalyticsServiceTests.swift
Increase minimum version and remove uneccesary availability checks.
This PR should not be merged until corresponding PRs in ios-components and onboarding are merged
> GOVUKAPP-1016: increase minimum version to 16.0

- GovUK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Includes: https://github.com/alphagov/govuk-mobile-ios-onboarding/pull/30
> Bumps onboarding revision

- Production/govuk_ios/Resources/Strings/Search.xcstrings
- Production/govuk_ios/ViewControllers/SearchViewController.swift
- Production/govuk_ios/Views/Search/SearchResultCell.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.SearchViewControllerSnapshotTests/test_search_successResponse_withResults_rendersCorrectly@3x.png
Adds search result header which is focused upon after results are returned.
> [GOVUKAPP-1028] Add search results header

- Production/govuk_ios/SwiftUIViews/AnalyticsConsentContainerView.swift
- Production/govuk_ios/SwiftUIViews/AppRecommendUpdateContainerView.swift
- Production/govuk_ios/SwiftUIViews/TopicsButtonView.swift
This pr removes the use of adaptive stack and instead uses Anylayout
> [GOVAPPUK-1055]-Remove adaptive stack

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Coordinators/HomeCoordinator.swift
- Production/govuk_ios/Extensions/Model/DeviceInformation+Convenience.swift
- Production/govuk_ios/ViewModels/SettingsViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/HomeCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Extensions/Model/DeviceInformationProvider+ConvenienceTests.swift
Extract help and feedback URL creation to convenience method and send device details with feedback widget
> GOVUKAPP-1106 send device details with user feedback

- Production/govuk_ios/Coordinators/HomeCoordinator.swift
- Production/govuk_ios/ViewModels/Topics/TopicsWidgetViewModel.swift
Update the stat text for feedback button
Hide "Show all topics" button if there is an error fetching topics
> post amigos fixes 28 jan

- .github/workflows/alpha.yml
- .github/workflows/beta.yml
- .github/workflows/pull_request.yml
- .github/workflows/schedule.yml
> Concurrency groups

- Production/govuk_ios/Services/NotificationService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Services/MockNotificationService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/NotificationServiceTests.swift
Some code commented because we will at some point remove this off switch
> GOVUKAPP-1203 Feature switch notifications

- GOVKit/Sources/GOVKit/Analytics/Model/ECommerceItem.swift
- GOVKit/Sources/GOVKit/ViewModels/GroupedListSection.swift
- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Extensions/Analytics/AppEvent+ECommerce.swift
- Production/govuk_ios/ViewModels/Topics/StepByStepsViewModel.swift
- Production/govuk_ios/ViewModels/Topics/TopicDetailViewModel.swift
- Production/govuk_ios/ViewModels/Topics/TopicDetailViewModelInterface.swift
- Production/govuk_ios/Views/Topics/TopicDetailView.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Analytics/AppEvent+EcommerceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/Topics/TopicDetailViewModelTests.swift
Add Ecommerce tracking to topics page.  See
https://docs.google.com/spreadsheets/d/1GJzMF7F3Xgujv2sowfNu3HyYGxmQ3rF3xqHye24rb-o/edit?pli=1&gid=1505057936#gid=1505057936
> govukapp-1142 topics e commerce tracking

- Production/govuk_ios/Extensions/Onboarding/OnboardingSlides+Convenience.swift
- Production/govuk_ios/Resources/Strings/Onboarding.xcstrings
- Removed accessibility hints for primary and secondary buttons
> Remove onboarding accessibility hints

- Production/govuk_ios/ViewControllers/SearchSuggestionsViewController.swift
- Production/govuk_ios/Views/Search/SearchHistoryCell.swift
- Production/govuk_ios/Views/Search/SuggestionCell.swift
Fixes shrinking magnifying glass for suggested / history cells
Allows words wrapping for suggested search header
> Fix search related accessibility issues

- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Builders/ViewControllerBuilder.swift
- Production/govuk_ios/Coordinators/HomeCoordinator.swift
- Production/govuk_ios/ViewControllers/HomeViewController.swift
- Production/govuk_ios/ViewModels/HomeViewModel.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_searchBarShouldBeginEditing_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_searchDisabled_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_searchEditing_cancelSearch_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.HomeViewControllerSnapshotTests/test_loadInNavigationController_searchEditing_resetState_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/HomeViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockViewControllerBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/ViewControllerBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/HomeCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewControllers/HomeContentViewControllerTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift
https://github.com/user-attachments/assets/a0e6f2c8-912e-4eb2-a36f-11318d8c17e5
> [GOVUKAPP-1251] Readd search feature flag

- GOVKit/Sources/GOVKit/SwiftUIViews/GroupedList/GroupedListRowView.swift
Combine title and detail as 1 accessibility element to fix issue
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-1299)
> GOVUKAPP-1299 App version number announced separately

- GOVKit/Sources/GOVKit/SwiftUIViews/GroupedList/GroupedListSectionIconView.swift
Ignore decorative grouped list header icon for accessibility
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-1298)
> GOVUKAPP-1298 Grouped list header icon

- sonar-project.properties
- Updated GOVKit sources to sonar properties
> GOVKit tests

- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/TopicOnboardingCoordinatorTests.swift
> Unused Variables

- GovUK.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Production/govuk_ios/Resources/Strings/LocalAuthority.xcstrings
- Production/govuk_ios/SwiftUIViews/CustomTextFieldBorder.swift
- Production/govuk_ios/ViewModels/LocalAuthorityPostcodeEntryViewModel.swift
- Production/govuk_ios/Views/Home/LocalAuthority/LocalAuthorityPostcodeEntryView.swift
- Production/govuk_ios/Views/Home/LocalAuthority/StoredLocalAuthorityWidgetView.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LocalAuthorityPostcodeEntryViewControllerSnapshotTests/test_loadInNavigationController_error_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LocalAuthorityPostcodeEntryViewControllerSnapshotTests/test_loadInNavigationController_error_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.StoredLocalAuthorityWidgetViewSnapshotTests/test_loadInNavigationController_twoTier_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.StoredLocalAuthorityWidgetViewSnapshotTests/test_loadInNavigationController_twoTier_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/Specs/ViewControllers/LocalAuthorityPostcodeEntryViewControllerSnapshotTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/LocalAuthorityPostcodeEntryViewmodelTests.swift
This pr adds error handling for invalid and unknown postcodes
> [GOVUKAPP-1353] Invalid and unknown postcodes

- Production/govuk_ios/Views/SignOut/AuthenticationInfoView.swift
set accessibility hidden on image on AuthenticationInfoView
> hide image from VO.

- Production/govuk_ios/Builders/CoordinatorBuilder.swift
- Production/govuk_ios/Coordinators/AppCoordinator.swift
- Production/govuk_ios/Coordinators/ReauthenticationCoordinator.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Builders/MockCoordinatorBuilder.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Builders/CoordinatorBuilderTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/ReauthenticationCoordinatorTests.swift
Handles the case if the app is in a signed out state and the app is cold launched.
> Start new user flow on reauth

- Production/govuk_ios/Resources/Strings/LocalAuthority.xcstrings
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LocalAuthorityPostcodeEntryViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LocalAuthorityPostcodeEntryViewControllerSnapshotTests/test_loadInNavigationController_error_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LocalAuthorityPostcodeEntryViewControllerSnapshotTests/test_loadInNavigationController_error_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LocalAuthorityPostcodeEntryViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
This pr updates the content on the postcode entry view
> GOVUKAPP-1711 Postcode entry content change

- GOVKit/Sources/GOVKit/Extensions/Constants.swift
- Production/govuk_ios/Model/LocalAuthority/LocalAuthorityAddress.swift
- Production/govuk_ios/Networking/GOVRequest/GOVRequest+LocalAuthority.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Networking/GOVRequest/GOVRequest+LocalAuthorityTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ServiceClients/LocalAuthorityServiceClientTests.swift
This pr updates integrates the real local authority api
> GOVUKAPP-1367 Update local api 

- Production/govuk_ios/Coordinators/EditLocalAuthorityCoordinator.swift
- Production/govuk_ios/SwiftUIViews/RadioButtonView.swift
- Production/govuk_ios/Views/Home/LocalAuthority/AmbiguousAddressSelectionView.swift
- Production/govuk_ios/Views/Home/LocalAuthority/AmbiguousAuthoritySelectionView.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AmbiguousAddressViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AmbiguousAddressViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AmbiguousAuthorityViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.AmbiguousAuthorityViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
Fix for back button in ambiguous authority flow not responding to dark mode.
Move Title/subtitle into scroll view with radio buttons so dynamic type works better at very large sizes.
> UI fixes for dark mode and dynamic type

- Production/govuk_ios/Resources/Strings/Home.xcstrings
* Updated topics alt text to "Edit your topics"
> Update Edit Topics alt text

- Production/govuk_ios/Resources/Strings/Settings.xcstrings
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.FaceIdSettingsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.FaceIdSettingsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TouchIdSettingsViewControllerSnapshotTests/test_loadInNavigationController_dark_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.TouchIdSettingsViewControllerSnapshotTests/test_loadInNavigationController_light_rendersCorrectly@3x.png
> Make biometrics settings content more generic

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Extensions/Views/AnimationView+Convenience.swift
- Production/govuk_ios/ViewControllers/LaunchViewController.swift
- Production/govuk_ios/Views/Common/AnimationView.swift
- Tests/govuk_ios/govuk_ios_snapshot_tests/ReferenceImages_64/govuk_ios_snapshot_tests.LaunchViewControllerSnapshotTests/test_loadInNavigationController_rendersCorrectly@3x.png
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Views/AnimationViewTests.swift
- Fixed crash in LaunchViewController when confirming notifications
- Reduced animations shows logo again on launch
- Update version -> 1.0.1
> GOVAPP-2062 Notifications crash hot fix

- Production/govuk_ios/Views/Chat/ChatCellView.swift
Minor color updates for chat links
> Minor color updates for chat links

- Production/govuk_ios/Resources/Config/Alpha.xcconfig
- Production/govuk_ios/Resources/Config/Debug.xcconfig
Staging environment has been rebuilt which means the creds have been updated.
> Update auth creds for alpha / debug

- Production/govuk_ios/Model/AppConfig/Feature.swift
> Add chat opt in feature flag

- GOVKit/Sources/GOVKit/Extensions/Constants.swift
- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Model/AppConfig/Config.swift
- Production/govuk_ios/Resources/Strings/Chat.xcstrings
- Production/govuk_ios/Services/AppConfigService.swift
- Production/govuk_ios/Services/ChatService.swift
- Production/govuk_ios/ViewModels/Chat/ChatOptInViewModel.swift
- Production/govuk_ios/ViewModels/Chat/ChatViewModel.swift
- Production/govuk_ios/Views/Chat/ChatActionView.swift
- Production/govuk_ios/Views/Chat/ChatMenuView.swift
- Production/govuk_ios/Views/Chat/ChatOptInView.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Arrangers/Model/Config+Arrangers.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Resources/MockAppConfigResponse.json
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ServiceClients/AppConfigServiceClientTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/ChatServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockAppConfigService.swift
- Tests/govuk_ios/shared/Mocks/Services/MockChatService.swift
Update AppConfigService and ChatService to get urls from remote configuration
Refactor ChatMenu into separate view
> govukapp-2292: add chat urls to config

- Production/govuk_ios/ViewModels/Chat/ChatViewModel.swift
Base loading of history on view appearance, on what kind of error was received
For any errors other than authentication errors, allow history to be reloaded.  This is so any pending questions that had been submitted will kick off again once the error is resolved.
For reauth errors, don't reload, as since we are retrying a request we can wind out of order results in a race between the history request and the question request.
> govukapp-2474:  Retry after error

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/Extensions/Analytics/AppEvent+Navigation.swift
- Production/govuk_ios/Model/AppConfig/Config.swift
- Production/govuk_ios/Services/AppConfigService.swift
- Production/govuk_ios/ViewModels/HomeViewModel.swift
- Production/govuk_ios/ViewModels/NotificationsWidgetViewModel.swift
- Production/govuk_ios/ViewModels/UserFeedbackWidgetViewModel.swift
- Production/govuk_ios/Views/Home/InformationView.swift
- Production/govuk_ios/Views/Home/UserFeedbackWidgetView.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Arrangers/Model/Config+Arrangers.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Extensions/Analytics/AppEvent+NavigationTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/HomeViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/UserFeedbackWidgetViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockAppConfigService.swift
- sonar-project.properties
[Jira link](https://govukverify.atlassian.net/browse/GOVUKAPP-2429)
[Figma link](https://www.figma.com/design/PqVTAh9m4NGMWBdyXgltzl/2025-07-GOV.UK-app-updates-to-public-beta?node-id=1826-86146&t=rdcOTACn0TTVUusn-0)
| Light mode | Dark mode |
|--------|-------|
| <img width="300" height="650" alt="Simulator Screenshot - iPhone 15 - 2025-09-03 at 15 21 42" src="https://github.com/user-attachments/assets/b43f1151-d5cf-4005-83f5-e3bc158fc493" /> | <img width="300" height="650" alt="Simulator Screenshot - iPhone 15 - 2025-09-03 at 15 22 02" src="https://github.com/user-attachments/assets/87c986b0-adbe-4e16-a969-90987ffa074c" /> |
> GOVUKAPP-2429 User feedback widget

- Production/govuk_ios/Model/AppConfig/Feature.swift
- Production/govuk_ios/Services/ChatService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/ChatServiceTests.swift
Rename flags to match remote config
> govukapp-2455: Use remote config chat flags

- Production/govuk_ios/Resources/Strings/Onboarding.xcstrings
- Production/govuk_ios/ViewModels/InfoViewModelInterface.swift
- Production/govuk_ios/ViewModels/WelcomeOnboardingViewModel.swift
- Production/govuk_ios/Views/Common/Info/InfoView.swift
Add accessibility label to loading indicator
> govukapp-2540:  Loading indicator alt-text

- Production/govuk_ios/Resources/Config/Release.xcconfig
Update URL as specified in 
https://govukverify.atlassian.net/browse/GOVUKAPP-2422
> govukapp-2422: Point chat at prod gateway for Release

- GovUK.xcodeproj/project.pbxproj
- Production/govuk_ios/ViewModels/RecentActivityViewModel/RecentActivityHomepageViewModel.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/RecentActivityWidgetHomepageViewmodelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/RecentActivtyHomepageWidgetViewModelTests.swift
- Removed unused variable warning
- Link fetch request and mapping limit
- Fix test class name
- Removed Recovered references
> Refactor RecentActivtyHomepageWidgetViewModel

- Production/govuk_ios/Coordinators/Chat/ChatCoordinator.swift
- Production/govuk_ios/Coordinators/Launch/AuthenticationCoordinator.swift
- Production/govuk_ios/Services/ChatService.swift
- Production/govuk_ios/Services/LocalAuthenticationService.swift
- Production/govuk_ios/ViewModels/Chat/ChatConsentOnboardingViewModel.swift
- Production/govuk_ios/ViewModels/Chat/ChatOffboardingViewModel.swift
- Production/govuk_ios/Views/Chat/ChatView.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Coordinators/ChatCoordinatorTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/ChatServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/LocalAuthenticationServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatCellViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatConsentOnboardingViewModelTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/ViewModels/ChatOffboardingViewModelTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockChatService.swift
- fixes edge case biometrics for returning user (face id skipped), ensures state is clear between users 
- clears chat onboarding on new user 
- serialize the flakey test
> Small fixes

- Production/govuk_ios/Extensions/Container/Container+Services.swift
- Production/govuk_ios/Model/AppConfig/Config.swift
- Production/govuk_ios/Services/Analytics/AnalyticsService.swift
- Production/govuk_ios/Services/AppConfigService.swift
- Production/govuk_ios/Services/AuthenticationService.swift
- Production/govuk_ios/Services/UserDefaultsService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Arrangers/Model/Config+Arrangers.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Mocks/Services/MockAppAttestService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Extensions/Container/Container+ServicesTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AnalyticsServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AppConfigServiceTests.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Specs/Services/AuthenticationServiceTests.swift
- Tests/govuk_ios/shared/Mocks/Services/MockAppConfigService.swift
> [GOVUKAPP-2590] Token Expiry

- Fastlane/.build.yml
- Updated sim device -> iPhone 16 Pro (18.6)
> Update unit test device

- Production/govuk_ios/Model/AppConfig/Config.swift
- Production/govuk_ios/Services/AppConfigService.swift
- Tests/govuk_ios/govuk_ios_unit_tests/Arrangers/Model/Config+Arrangers.swift
- Add support for decimal chat polling intervals
> [GOVUKAPP-2606] - Chat interval decimals
